#!/bin/bash

# С помощью imagemagick делаем скриншот выбранной области, отдаем его в pipe
# копируем его из pipe в буфер обмена с помощью xclip
# import png:- | xclip -selection c -t image/png
curr_date=`(date +"%d-%m-%Y_%H-%M-%S")`
import /media/d/screenshots/$curr_date.png &&
cat /media/d/screenshots/$curr_date.png | xclip -selection c -t image/png
 
