#!/bin/bash

# С помощью imagemagick делаем скриншот выбранной области, отдаем его в pipe
# копируем его из pipe в буфер обмена с помощью xclip
# import png:- | xclip -selection c -t image/png

curr_date=`(date +"%d-%m-%Y_%H-%M-%S")`

# Using import
import $SCREENSHOT_DIR/area/$curr_date.png &&

# Using scrot
# scrot -s -z $curr_date.png -e "mv $f $SCREENSHOT_DIR/area/" &&
cat $SCREENSHOT_DIR/area/$curr_date.png | xclip -selection c -t image/png

