#!/bin/bash

# Делаем скриншот выбранной области
# Делаем пост запрос с этой картинкой на хостинг с помощью курла, парсим ответ через jq
# и копируем полученную ссылку на скриншот в буфер обмена

import /home/gel0/screenshoot.png &&

sudo curl -s \
-F "source=@screenshoot.png" \
-F "type=file" \
-F "action=upload" \
-X POST \
https://ru.imgbb.com/json | jq -r ".image" | jq -r ".url" | xclip -selection clipboard;

sudo rm ~/screenshoot.png
