#!/bin/bash

# С помощью imagemagick делаем скриншот всего окна, отдаем его в pipe
# копируем его из pipe в буфер обмена с помощью xclip

# import -window root screen.ps png:- | xclip -selection c -t image/png

curr_date=`(date +"%d-%m-%Y_%H-%M-%S")`

# Using 'import'
# import -window root /media/d/screenshots/full/$curr_date.png &&  

# Using scrot
scrot $curr_date.png -e 'mv $f /media/d/screenshots/full/'
cat /media/d/screenshots/full/$curr_date.png | xclip -selection c -t image/png

