#!/bin/bash

# С помощью imagemagick делаем скриншот всего окна, отдаем его в pipe
# копируем его из pipe в буфер обмена с помощью xclip

import -window root screen.ps png:- | xclip -selection c -t image/png

# curr_date=`(date +"%Y-%m-%d_%H-%M-%S")`
# import -window root /media/d/screenshots/$curr_date.png 

